export type ColumnDef = {
  key: string;
  label: string;
  defaultVisible: boolean;
  locked?: boolean;
};

export const TABLE_COLUMN_DEFS: Record<string, ColumnDef[]> = {
  budget: [
    { key: "checkbox",    label: "เลือก",         defaultVisible: true, locked: true },
    { key: "code",        label: "Cost Code",     defaultVisible: true },
    { key: "description", label: "รายการ",        defaultVisible: true },
    { key: "budget",      label: "Budget",        defaultVisible: true },
    { key: "status",      label: "สถานะ",         defaultVisible: true },
    { key: "attachment",  label: "Attachment",     defaultVisible: true },
    { key: "balance",     label: "Balance",        defaultVisible: true },
    { key: "prTotal",     label: "PR Total",       defaultVisible: true },
    { key: "poTotal",     label: "PO Total",       defaultVisible: true },
    { key: "nowStatus",   label: "Now Status",     defaultVisible: true },
    { key: "actions",     label: "Actions",        defaultVisible: true, locked: true },
  ],
  "dash-budget": [
    { key: "checkbox",    label: "เลือก",         defaultVisible: true, locked: true },
    { key: "costCode",    label: "Cost Code",     defaultVisible: true },
    { key: "description", label: "รายการ",        defaultVisible: true },
    { key: "amount",      label: "จำนวนเงิน",     defaultVisible: true },
    { key: "status",      label: "สถานะ",         defaultVisible: true },
    { key: "actions",     label: "Actions",        defaultVisible: true, locked: true },
  ],
  "dash-subitem": [
    { key: "costCode",    label: "Cost Code",      defaultVisible: true },
    { key: "description", label: "รายการ",         defaultVisible: true },
    { key: "amount",      label: "จำนวนเงินรวม",    defaultVisible: true },
    { key: "status",      label: "สถานะ",          defaultVisible: true },
    { key: "actions",     label: "Actions",         defaultVisible: true, locked: true },
  ],
  "dash-pr": [
    { key: "prNo",      label: "PR No.",        defaultVisible: true },
    { key: "date",      label: "วันที่",         defaultVisible: true },
    { key: "costCode",  label: "Cost Code",     defaultVisible: true },
    { key: "type",      label: "ประเภท",        defaultVisible: true },
    { key: "requestor", label: "ผู้ขอซื้อ",      defaultVisible: true },
    { key: "amount",    label: "จำนวนเงิน",     defaultVisible: true },
    { key: "status",    label: "สถานะ",         defaultVisible: true },
    { key: "actions",   label: "Actions",        defaultVisible: true, locked: true },
  ],
  "dash-po": [
    { key: "poNo",     label: "PO No.",        defaultVisible: true },
    { key: "date",     label: "วันที่",         defaultVisible: true },
    { key: "costCode", label: "Cost Code",     defaultVisible: true },
    { key: "amount",   label: "จำนวนเงิน",     defaultVisible: true },
    { key: "status",   label: "สถานะ",         defaultVisible: true },
    { key: "actions",  label: "Actions",        defaultVisible: true, locked: true },
  ],
  pr: [
    { key: "prNo",        label: "PR No.",       defaultVisible: true },
    { key: "date",        label: "Date",         defaultVisible: true },
    { key: "costCode",    label: "Cost Code",    defaultVisible: true },
    { key: "description", label: "Description",  defaultVisible: true },
    { key: "type",        label: "Type",         defaultVisible: true },
    { key: "requestor",   label: "Requestor",    defaultVisible: true },
    { key: "items",       label: "Items",        defaultVisible: true },
    { key: "amount",      label: "Amount",       defaultVisible: true },
    { key: "balance",     label: "Balance",      defaultVisible: true },
    { key: "status",      label: "Status",       defaultVisible: true },
    { key: "refDoc",      label: "Ref Doc",      defaultVisible: true },
    { key: "actions",     label: "Actions",      defaultVisible: true, locked: true },
  ],
  po: [
    { key: "poNo",        label: "PO No.",         defaultVisible: true },
    { key: "poType",      label: "Type",           defaultVisible: true },
    { key: "prNos",       label: "Ref PR No.",     defaultVisible: true },
    { key: "description", label: "Description PR", defaultVisible: true },
    { key: "vendor",      label: "Vendor",         defaultVisible: true },
    { key: "creator",     label: "ผู้เปิด/สร้าง PO", defaultVisible: true },
    { key: "items",       label: "Item",           defaultVisible: true },
    { key: "amount",      label: "Amount",         defaultVisible: true },
    { key: "status",      label: "Status",         defaultVisible: true },
    { key: "actions",     label: "Action",         defaultVisible: true, locked: true },
  ],
  "select-items": [
    { key: "pick",        label: "เลือก",          defaultVisible: true, locked: true },
    { key: "prNo",        label: "PR No.",        defaultVisible: true },
    { key: "status",      label: "สถานะ",         defaultVisible: true },
    { key: "materialNo",  label: "Material No.",  defaultVisible: true },
    { key: "description", label: "รายการ",        defaultVisible: true },
    { key: "unit",        label: "หน่วย",         defaultVisible: true },
    { key: "orderQty",    label: "สั่งซื้อ (QTY)", defaultVisible: true },
    { key: "price",       label: "ราคา/หน่วย",    defaultVisible: true },
    { key: "total",       label: "รวม",           defaultVisible: true },
    { key: "disPr",       label: "Dis PR",        defaultVisible: true },
  ],
  "select-pr": [
    { key: "checkbox",    label: "เลือก",         defaultVisible: true, locked: true },
    { key: "prNo",        label: "PR No.",       defaultVisible: true },
    { key: "costCode",    label: "Cost Code",    defaultVisible: true },
    { key: "description", label: "รายการงบ",      defaultVisible: true },
    { key: "requestor",   label: "ผู้ขอซื้อ",     defaultVisible: true },
    { key: "date",        label: "วันที่",        defaultVisible: true },
    { key: "items",       label: "สินค้า",        defaultVisible: true },
    { key: "amount",      label: "ยอดรวม",       defaultVisible: true },
  ],
  project: [
    { key: "jobNo",         label: "Job No.",         defaultVisible: true },
    { key: "name",          label: "Project Name",    defaultVisible: true },
    { key: "location",      label: "Location",        defaultVisible: true },
    { key: "projectStatus", label: "Project Status",  defaultVisible: true },
    { key: "budgetValue",   label: "Budget Value",    defaultVisible: true },
    { key: "contractValue", label: "Contract Value",  defaultVisible: true },
    { key: "start",         label: "Start",           defaultVisible: true },
    { key: "finish",        label: "Finish",          defaultVisible: true },
    { key: "pm",            label: "PM",              defaultVisible: true },
    { key: "cm",            label: "CM",              defaultVisible: true },
    { key: "projectType",   label: "Project Type",    defaultVisible: true },
    { key: "actions",       label: "Actions",         defaultVisible: true, locked: true },
  ],
  vendor: [
    { key: "select",     label: "เลือก",         defaultVisible: true, locked: true },
    { key: "rowNo",      label: "ลำดับ",         defaultVisible: true },
    { key: "code",       label: "รหัส",          defaultVisible: true },
    { key: "name",       label: "ชื่อ",          defaultVisible: true },
    { key: "address",    label: "ที่อยู่",        defaultVisible: true },
    { key: "tel",        label: "โทร",           defaultVisible: true },
    { key: "creditTerm", label: "เครดิตเทอม",    defaultVisible: true },
    { key: "actions",    label: "Actions",        defaultVisible: true, locked: true },
  ],
  material: [
    { key: "select",     label: "เลือก",          defaultVisible: true, locked: true },
    { key: "rowNo",      label: "No.",            defaultVisible: true },
    { key: "materialNo", label: "รหัสสินค้า",     defaultVisible: true },
    { key: "name",       label: "ชื่อสินค้า",      defaultVisible: true },
    { key: "price",      label: "ราคาต่อหน่วย",   defaultVisible: true },
    { key: "unit",       label: "หน่วย",          defaultVisible: true },
    { key: "actions",    label: "Actions",         defaultVisible: true, locked: true },
  ],
  invoice: [
    { key: "invNo",       label: "INV No.",      defaultVisible: true },
    { key: "poRef",       label: "Ref. PO",      defaultVisible: true },
    { key: "description", label: "รายละเอียด",    defaultVisible: true },
    { key: "amount",      label: "จำนวนเงิน",    defaultVisible: true },
    { key: "status",      label: "สถานะ",        defaultVisible: true },
    { key: "actions",     label: "Actions",       defaultVisible: true, locked: true },
  ],
  payment: [
    { key: "paymentNo",   label: "Payment No.",  defaultVisible: true },
    { key: "type",        label: "Type",         defaultVisible: true },
    { key: "contractor",  label: "ผู้รับเหมา",    defaultVisible: true },
    { key: "billingCycle", label: "รอบวางบิล",   defaultVisible: true },
    { key: "amount",      label: "ยอดรวม",       defaultVisible: true },
    { key: "status",      label: "Status",       defaultVisible: true },
    { key: "actions",     label: "Action",       defaultVisible: true, locked: true },
  ],
  "payment-table": [
    { key: "paymentNo",    label: "Payment No.",  defaultVisible: true },
    { key: "type",         label: "Type",         defaultVisible: true },
    { key: "contractor",   label: "ผู้รับเหมา",    defaultVisible: true },
    { key: "billingCycle", label: "รอบวางบิล",    defaultVisible: true },
    { key: "openDate",     label: "วันที่เปิด",    defaultVisible: true },
    { key: "amount",       label: "ยอดรวม",       defaultVisible: true },
    { key: "attachment",   label: "เอกสาร",       defaultVisible: true },
    { key: "status",       label: "Status",       defaultVisible: true },
    { key: "actions",      label: "Action",       defaultVisible: true, locked: true },
  ],
  "pr-table": [
    { key: "rowNum",      label: "#",              defaultVisible: true, locked: true },
    { key: "no",          label: "PR No.",         defaultVisible: true },
    { key: "project",     label: "โครงการ",        defaultVisible: true },
    { key: "costCode",    label: "Cost Code",      defaultVisible: true },
    { key: "description", label: "รายการงบ",       defaultVisible: true },
    { key: "date",        label: "วันที่",          defaultVisible: true },
    { key: "requestor",   label: "ผู้ขอ",          defaultVisible: true },
    { key: "type",        label: "ประเภท",         defaultVisible: true },
    { key: "items",       label: "จำนวนรายการ",    defaultVisible: true },
    { key: "amount",      label: "ยอดรวม",         defaultVisible: true },
    { key: "balance",     label: "Balance",        defaultVisible: true },
    { key: "status",      label: "สถานะ",          defaultVisible: true },
    { key: "poRef",       label: "Ref PO",         defaultVisible: true },
    { key: "action",      label: "Action",         defaultVisible: true, locked: true },
  ],
  "po-table": [
    { key: "rowNum",   label: "#",             defaultVisible: true, locked: true },
    { key: "no",       label: "PO No.",        defaultVisible: true },
    { key: "project",  label: "โครงการ",       defaultVisible: true },
    { key: "costCode", label: "Cost Code",     defaultVisible: true },
    { key: "vendor",   label: "Vendor",        defaultVisible: true },
    { key: "prRef",    label: "Ref PR No.",    defaultVisible: true },
    { key: "date",     label: "วันที่",         defaultVisible: true },
    { key: "items",    label: "จำนวนรายการ",   defaultVisible: true },
    { key: "amount",   label: "ยอดรวม",        defaultVisible: true },
    { key: "status",   label: "สถานะ",         defaultVisible: true },
    { key: "action",   label: "Action",        defaultVisible: true, locked: true },
  ],
  users: [
    { key: "name",     label: "Name",       defaultVisible: true },
    { key: "role",     label: "Role",       defaultVisible: true },
    { key: "status",   label: "Status",     defaultVisible: true },
    { key: "projects", label: "Projects",   defaultVisible: true },
    { key: "actions",  label: "Actions",    defaultVisible: true, locked: true },
  ],
  "receive-po": [
    { key: "poNo",        label: "PO No.",       defaultVisible: true },
    { key: "vendor",      label: "Vendor",       defaultVisible: true },
    { key: "description", label: "รายละเอียด",    defaultVisible: true },
    { key: "amount",      label: "ยอดรวม",       defaultVisible: true },
    { key: "progress",    label: "สถานะรับของ",  defaultVisible: true },
    { key: "actions",     label: "Actions",      defaultVisible: true, locked: true },
  ],
  "receive-history": [
    { key: "rpNo",       label: "RP No.",        defaultVisible: true },
    { key: "date",       label: "วันที่ทำรับ",    defaultVisible: true },
    { key: "poNo",       label: "PO No.",        defaultVisible: true },
    { key: "type",       label: "Type",          defaultVisible: true },
    { key: "vendor",     label: "Vendor",        defaultVisible: true },
    { key: "items",      label: "รายการสินค้า",   defaultVisible: true },
    { key: "receivedBy", label: "ผู้รับของ",      defaultVisible: true },
    { key: "note",       label: "หมายเหตุ",       defaultVisible: true },
    { key: "actions",    label: "Actions",        defaultVisible: true, locked: true },
  ],
};

export function getDefaultVisibility(tableId: string): Record<string, boolean> {
  const defs = TABLE_COLUMN_DEFS[tableId];
  if (!defs) return {};
  const out: Record<string, boolean> = {};
  defs.forEach((d) => { out[d.key] = d.defaultVisible; });
  return out;
}
